export const fallbackInternships = [
  {
    id: 65532,
    title: "Data Science Intern",
    company_name: "Google",
    company_logo: "6385f8a1c006b1669724321.png",
    work_from_home: false,
    location_names: ["Munnar", "Delhi", "Lucknow", "Tarn Taran"],
    duration: "3 Months",
    stipend: {
      salary: "₹ 50,000 /month",
      salaryValue1: 50000,
    },
    start_date: "Starts Immediately",
    posted_by_label: "Today",
    is_ppo: true,
    ppo_label_value: "With job offer (PPO)",
    part_time: false,
  },
  {
    id: 65454,
    title: "Administration Intern (Remote)",
    company_name: "Decoy Enterprise",
    company_logo: "",
    work_from_home: true,
    location_names: [],
    duration: "3 Months",
    stipend: {
      salary: "₹ 30,000 /month",
      salaryValue1: 30000,
    },
    start_date: "Starts Immediately",
    posted_by_label: "3 days ago",
    is_ppo: false,
    ppo_label_value: null,
    part_time: false,
  },
  {
    id: 65501,
    title: "Android App Development Intern",
    company_name: "Engineering Solutions",
    company_logo: "",
    work_from_home: false,
    location_names: ["Gurgaon"],
    duration: "2 Months",
    stipend: {
      salary: "₹ 20,000 /month",
      salaryValue1: 20000,
    },
    start_date: "Starts Immediately",
    posted_by_label: "6 days ago",
    is_ppo: false,
    ppo_label_value: "With job offer",
    part_time: false,
  },
  {
    id: 65504,
    title: "Product Management Intern",
    company_name: "Engineering Solutions",
    company_logo: "",
    work_from_home: false,
    location_names: ["Gurgaon"],
    duration: "3 Months",
    stipend: {
      salary: "₹ 10,000 /month",
      salaryValue1: 10000,
    },
    start_date: "Starts Immediately",
    posted_by_label: "6 days ago",
    is_ppo: false,
    ppo_label_value: "With job offer",
    part_time: true,
  },
  {
    id: 65515,
    title: "Web Development Intern",
    company_name: "Meta",
    company_logo: "",
    work_from_home: true,
    location_names: [],
    duration: "6 Months",
    stipend: {
      salary: "₹ 45,000 /month",
      salaryValue1: 45000,
    },
    start_date: "Starts Immediately",
    posted_by_label: "2 days ago",
    is_ppo: true,
    ppo_label_value: "With job offer (PPO)",
    part_time: false,
  },
  {
    id: 65517,
    title: "UI/UX Design Intern",
    company_name: "Netflix",
    company_logo: "",
    work_from_home: false,
    location_names: ["Mumbai", "Bangalore"],
    duration: "4 Months",
    stipend: {
      salary: "₹ 35,000 /month",
      salaryValue1: 35000,
    },
    start_date: "Starts Immediately",
    posted_by_label: "Yesterday",
    is_ppo: false,
    ppo_label_value: null,
    part_time: false,
  },
  {
    id: 65522,
    title: "Full Stack Developer Intern",
    company_name: "Amazon",
    company_logo: "",
    work_from_home: false,
    location_names: ["Bangalore"],
    duration: "6 Months",
    stipend: {
      salary: "₹ 40,000 /month",
      salaryValue1: 40000,
    },
    start_date: "Starts Immediately",
    posted_by_label: "4 days ago",
    is_ppo: true,
    ppo_label_value: "With job offer (PPO)",
    part_time: false,
  },
  {
    id: 65524,
    title: "Marketing & Strategy Intern",
    company_name: "Microsoft",
    company_logo: "",
    work_from_home: true,
    location_names: [],
    duration: "3 Months",
    stipend: {
      salary: "₹ 25,000 /month",
      salaryValue1: 25000,
    },
    start_date: "Starts Immediately",
    posted_by_label: "5 days ago",
    is_ppo: false,
    ppo_label_value: null,
    part_time: true,
  },
  {
    id: 65531,
    title: "Research Intern - Machine Learning",
    company_name: "OpenAI",
    company_logo: "",
    work_from_home: true,
    location_names: [],
    duration: "6 Months",
    stipend: {
      salary: "₹ 50,000 /month",
      salaryValue1: 50000,
    },
    start_date: "Starts Immediately",
    posted_by_label: "Today",
    is_ppo: true,
    ppo_label_value: "With job offer (PPO)",
    part_time: false,
  },
  {
    id: 65381,
    title: "Cyber Security Associate Intern",
    company_name: "Palo Alto Networks",
    company_logo: "",
    work_from_home: false,
    location_names: ["Pune"],
    duration: "6 Months",
    stipend: {
      salary: "₹ 30,000 /month",
      salaryValue1: 30000,
    },
    start_date: "Starts Immediately",
    posted_by_label: "1 week ago",
    is_ppo: false,
    ppo_label_value: null,
    part_time: false,
  }
];
