export const fallbackInternships = [
  {
    id: 101,
    title: "Software Development Engineering (Web)",
    company_name: "Emoolar Technology Private Limited",
    company_logo: "",
    work_from_home: true,
    location_names: [],
    duration: "6 Months",
    stipend: {
      salary: "₹ 3,500 - 6,000 /month",
      salaryValue1: 3500,
    },
    start_date: "Starts Immediately",
    posted_by_label: "1 day ago",
    is_ppo: true,
    ppo_label_value: "Job offer upto ₹ 3.1LPA post internship",
    part_time: true,
    description: "Collaborate on web application design, development, maintenance, and optimization using HTML...",
    skills: ["HTML", "CSS", "JavaScript"]
  },
  {
    id: 102,
    title: "AI Agent Development",
    company_name: "Primetrade.ai",
    company_logo: "",
    work_from_home: true,
    location_names: [],
    duration: "6 Months",
    stipend: {
      salary: "₹ 10,000 /month",
      salaryValue1: 10000,
    },
    start_date: "Starts Immediately",
    posted_by_label: "Today",
    is_ppo: true,
    ppo_label_value: "Job offer starting ₹ 3LPA post internship",
    is_early_applicant: true,
    part_time: false,
    description: "Build tool-using agent workflows and implement tool wrappers with retries, timeouts, validation, ...",
    skills: ["Python", "Software Testing"]
  },
  {
    id: 103,
    title: "Front End Development",
    company_name: "NayePankh Foundation",
    company_logo: "",
    work_from_home: true,
    location_names: [],
    duration: "1 Week",
    stipend: {
      salary: "Unpaid",
      salaryValue1: 0,
    },
    start_date: "Starts Immediately",
    posted_by_label: "Few hours ago",
    is_ppo: true,
    ppo_label_value: "Job offer post internship",
    part_time: true,
    description: "Design and develop interactive web applications using HTML, create responsive designs, and opt...",
    skills: ["HTML", "CSS", "JavaScript"]
  },
  {
    id: 104,
    title: "Web Development",
    company_name: "Basti Ki Pathshala Foundation",
    company_logo: "",
    work_from_home: true,
    location_names: [],
    duration: "1 Week",
    stipend: {
      salary: "Unpaid",
      salaryValue1: 0,
    },
    start_date: "Starts Immediately",
    posted_by_label: "Few hours ago",
    is_ppo: true,
    ppo_label_value: "Job offer post internship",
    part_time: true,
    description: "Assist in website creation, maintenance, optimization, and troubleshooting for the organization",
    skills: ["HTML", "CSS", "JavaScript"]
  },
  {
    id: 65532,
    title: "Data Science Intern",
    company_name: "Google",
    company_logo: "6385f8a1c006b1669724321.png",
    work_from_home: false,
    location_names: ["Munnar", "Delhi", "Lucknow"],
    duration: "3 Months",
    stipend: {
      salary: "₹ 50,000 /month",
      salaryValue1: 50000,
    },
    start_date: "Starts Immediately",
    posted_by_label: "Today",
    is_ppo: true,
    ppo_label_value: "Job offer post internship",
    part_time: false,
    description: "Build deep learning neural networks, process large analytics datasets, and deploy machine learning models at scale.",
    skills: ["Python", "SQL", "TensorFlow", "Data Science"]
  },
  {
    id: 65515,
    title: "Web Development Intern",
    company_name: "Meta",
    company_logo: "",
    work_from_home: true,
    location_names: [],
    duration: "6 Months",
    stipend: {
      salary: "₹ 45,000 /month",
      salaryValue1: 45000,
    },
    start_date: "Starts Immediately",
    posted_by_label: "2 days ago",
    is_ppo: true,
    ppo_label_value: "Job offer post internship",
    part_time: false,
    description: "Develop robust frontend components using React 19, maintain API endpoints, and collaborate closely with product design.",
    skills: ["React", "JavaScript", "CSS", "Node.js"]
  }
];
