export const fallbackInternships = [
  {
    id: 10001,
    title: "Web Development",
    company_name: "Basti Ki Pathshala Foundation",
    company_logo: "",
    work_from_home: true,
    location_names: [],
    duration: "1 Week",
    stipend: {
      salary: "Unpaid",
      salaryValue1: 0,
    },
    start_date: "Starts Immediately",
    posted_by_label: "Few hours ago",
    is_ppo: true,
    ppo_label_value: "Job offer post internship",
    part_time: true,
    description: "Assist in website creation, maintenance, optimization, and troubleshooting for the organization",
    skills: ["HTML"]
  },
  {
    id: 10002,
    title: "Artificial Intelligence (AI)",
    company_name: "NayePankh Foundation",
    company_logo: "",
    work_from_home: true,
    location_names: [],
    duration: "1 Month",
    stipend: {
      salary: "Unpaid",
      salaryValue1: 0,
    },
    start_date: "Starts Immediately",
    posted_by_label: "Few hours ago",
    is_ppo: true,
    ppo_label_value: "Job offer post internship",
    part_time: true,
    description: "Develop and implement AI algorithms, conduct research, and integrate solutions using ChatGPT, Claude, and Gemini",
    skills: ["Artificial intelligence", "ChatGPT", "Claude", "Gemini"]
  },
  {
    id: 10003,
    title: "Front End Development",
    company_name: "Basti Ki Pathshala Foundation",
    company_logo: "",
    work_from_home: true,
    location_names: [],
    duration: "1 Month",
    stipend: {
      salary: "Unpaid",
      salaryValue1: 0,
    },
    start_date: "Starts Immediately",
    posted_by_label: "Few hours ago",
    is_ppo: true,
    ppo_label_value: "Job offer post internship",
    part_time: true,
    description: "Collaborate with design team to implement website mockups using HTML, ensuring responsive layouts and perfect design integration",
    skills: ["HTML", "CSS", "JavaScript"]
  },
  {
    id: 65532,
    title: "Data Science Intern",
    company_name: "Google",
    company_logo: "6385f8a1c006b1669724321.png",
    work_from_home: false,
    location_names: ["Munnar", "Delhi", "Lucknow"],
    duration: "3 Months",
    stipend: {
      salary: "₹ 50,000 /month",
      salaryValue1: 50000,
    },
    start_date: "Starts Immediately",
    posted_by_label: "Today",
    is_ppo: true,
    ppo_label_value: "Job offer post internship",
    part_time: false,
    description: "Build deep learning neural networks, process large analytics datasets, and deploy machine learning models at scale.",
    skills: ["Python", "SQL", "TensorFlow", "Data Science"]
  },
  {
    id: 65515,
    title: "Web Development Intern",
    company_name: "Meta",
    company_logo: "",
    work_from_home: true,
    location_names: [],
    duration: "6 Months",
    stipend: {
      salary: "₹ 45,000 /month",
      salaryValue1: 45000,
    },
    start_date: "Starts Immediately",
    posted_by_label: "2 days ago",
    is_ppo: true,
    ppo_label_value: "Job offer post internship",
    part_time: false,
    description: "Develop robust frontend components using React 19, maintain API endpoints, and collaborate closely with product design.",
    skills: ["React", "JavaScript", "CSS", "Node.js"]
  },
  {
    id: 65517,
    title: "UI/UX Design Intern",
    company_name: "Netflix",
    company_logo: "",
    work_from_home: false,
    location_names: ["Mumbai", "Bangalore"],
    duration: "4 Months",
    stipend: {
      salary: "₹ 35,000 /month",
      salaryValue1: 35000,
    },
    start_date: "Starts Immediately",
    posted_by_label: "Yesterday",
    is_ppo: false,
    ppo_label_value: null,
    part_time: false,
    description: "Conduct high-fidelity user research, design wireframes in Figma, and build premium prototype flows.",
    skills: ["Figma", "UI/UX", "Prototyping", "User Research"]
  }
];
